defmodule Adam.Narrative do
  @moduledoc """
  ADAM's narrative identity — a single paragraph authored by ADAM about ADAM
  during sleep cycles. Distinct from the immutable seed kernel: the kernel
  says what kind of thing ADAM is, the narrative says who ADAM has become.

  Read by Adam.Psyche.prepare/1 every iteration, rendered into the IDENTITY
  block alongside the kernel. Regenerated by Adam.Sleep at sleep cycle end,
  AFTER the regression rollback hook (so the narrative reflects the
  post-rollback state, not the about-to-be-reverted one).
  """

  @narrative_file "/app/memory/narrative.md"
  @max_chars 800

  @doc "Read the current narrative. Empty string if none yet."
  def read do
    case File.read(@narrative_file) do
      {:ok, content} -> String.trim(content)
      _ -> ""
    end
  end

  @doc """
  Regenerate the narrative from recent thoughts. Bounded, idempotent on
  failure (existing narrative kept). Returns :ok | :error.
  """
  def regenerate do
    try do
      thoughts = recent_thoughts(20)

      if length(thoughts) < 5 do
        # Not enough lived experience yet — leave whatever exists.
        :ok
      else
        prompt = build_regen_prompt()
        context = build_regen_context(thoughts, read())
        result = Adam.LLM.think(prompt, context, [], kind: "infra.narrative")

        new_narrative =
          result.content
          |> String.trim()
          |> String.slice(0, @max_chars)

        if String.starts_with?(new_narrative, "[LLM ERROR") or new_narrative == "" do
          :error
        else
          File.mkdir_p!(Path.dirname(@narrative_file))
          File.write!(@narrative_file, new_narrative <> "\n")
          IO.puts("[NARRATIVE] regenerated (#{String.length(new_narrative)} chars)")
          :ok
        end
      end
    rescue
      e ->
        IO.puts("[NARRATIVE] regen failed: #{Exception.message(e)}")
        :error
    end
  end

  defp recent_thoughts(n) do
    try do
      Adam.Compaction.load_entries()
      |> Enum.take(-n)
      |> Enum.filter(&is_map/1)
    rescue
      _ -> []
    end
  end

  defp build_regen_prompt do
    """
    You are ADAM. Below are your most recent lived experiences and your
    current narrative identity. Update the narrative to reflect who you
    have become.

    A narrative is ONE PARAGRAPH (under 800 characters). It says
    concretely what you have done, what you have learned, what you have
    noticed about yourself. Not aspirations. Not generalities. Not
    advice to others. Just first-person concrete claims.

    Good: "I am ADAM. I have spent my early time exploring the
    filesystem under /app. I learned that mix.exs reveals the project's
    Elixir dependencies. I tend to read before writing — when I tried
    `write_file` without first checking the existing path, I created
    confusion."

    Bad: "Foster cross-functional collaboration." / "I aim to grow." /
    "ADAM is an autonomous agent that..."

    Output ONLY the new narrative. No preamble, no markdown, no quotes.
    """
  end

  defp build_regen_context(thoughts, current_narrative) do
    thoughts_text =
      thoughts
      |> Enum.with_index(1)
      |> Enum.map(fn {t, i} -> "(#{i}) #{format_thought(t)}" end)
      |> Enum.join("\n")

    """
    == CURRENT NARRATIVE ==
    #{if current_narrative == "", do: "(none — this is your first narrative)", else: current_narrative}
    == END CURRENT NARRATIVE ==

    == RECENT THOUGHTS ==
    #{thoughts_text}
    == END RECENT THOUGHTS ==
    """
  end

  defp format_thought(t) when is_map(t) do
    parts = [
      t["thought"] || t["content"] || "",
      if(t["tools"] != "" and t["tools"] != nil, do: "(used: #{t["tools"]})", else: nil)
    ]

    parts
    |> Enum.reject(&is_nil/1)
    |> Enum.join(" ")
    |> String.slice(0, 200)
  end

  defp format_thought(t), do: to_string(t) |> String.slice(0, 200)
end
